# Describes the format for available pyscript services

reload:
  description: Reload all available pyscripts and restart triggers
  fields:
    global_ctx:
      description: only reload this specific global context (file or app)
      example: file.example
      required: false
      selector:
        text:

jupyter_kernel_start:
  description: Start a jupyter kernel for interactive use; called by Jupyter front end
  fields:
    shell_port:
      description: shell port number
      example: 63599
      required: false
      selector:
        number:
          min: 49152
          max: 65535
    iopub_port:
      description: iopub port number
      example: 63598
      required: false
      selector:
        number:
          min: 49152
          max: 65535
    stdin_port:
      description: stdin port number
      example: 63597
      required: false
      selector:
        number:
          min: 49152
          max: 65535
    control_port:
      description: control port number
      example: 63596
      required: false
      selector:
        number:
          min: 49152
          max: 65535
    hb_port:
      description: heartbeat port number
      example: 63595
      required: false
      selector:
        number:
          min: 49152
          max: 65535
    ip:
      description: ip address to connect to jupyter front end
      example: 127.0.0.1
      default: 127.0.0.1
      required: false
      selector:
        text:
    key:
      description: security key for signing
      example: 012345678-9abcdef023456789abcdef
      required: true
      selector:
        text:
    transport:
      description: type of transport
      example: tcp
      default: tcp
      required: false
      selector:
        select:
          options:
            - tcp
            - udp
    signature_scheme:
      description: signing algorithm
      example: hmac-sha256
      required: false
      default: hmac-sha256
      selector:
        select:
          options:
            - hmac-sha256
    kernel_name:
      description: name of kernel
      example: pyscript
      required: true
      default: pyscript
      selector:
        text:
